### PR TITLE
fix: Forward native error details to webview

### LINKED ISSUE #98: Forward Error To Webview
In React Native, if a function throws an error, the error is not passed, but the function resolves `null` in the webview.

```ts
import { createWebView, bridge } from "@webview-bridge/react-native";
import InAppBrowser from "react-native-inappbrowser-reborn";

// Register functions in the bridge object in your React Native code
export const appBridge = bridge({
  async openInAppBrowser(url: string) {
    if (await InAppBrowser.isAvailable()) {
      await InAppBrowser.open(url);
    } else {
       throw new Error("InAppBrowser is not available")
    }
  },
  // ... Add more functions as needed
});

// Export the bridge type to be used in the web application
export type AppBridge = typeof appBridge;
```

### Currently 
```ts
import { linkBridge } from "@webview-bridge/web";
import type { AppBridge } from ""; // Import the type 'appBridge' declared in native

...

bridge.openInAppBrowser("http://localhost:5173").then((message) => console.log(message)); // "null"
```

### Expected
```ts
import { linkBridge } from "@webview-bridge/web";
import type { AppBridge } from ""; // Import the type 'appBridge' declared in native

...

bridge.openInAppBrowser("http://localhost:5173").catch((err) => console.log(message)); // "Error: InAppBrowser is not available"
```

### PR DESCRIPTION
**Pull request by dioKR**
**Summary**
- Native errors now forward actual error details (message, name, stack) to webview
- Previously only generic NativeMethodError was received

**Changes**
- Add serializeError / deserializeError to pass error details between native and web
- Fix deserializeError to parse JSON string from native

**Before**

https://github.com/user-attachments/assets/f16a7482-9d56-422a-971d-c750ba3c5fe2

**After**

https://github.com/user-attachments/assets/4c5e7f54-10b0-48e7-aa3d-18775812dcba

## Note
Added `throwError` test method in example/native-method folder for testing. 
Let me know if this should be removed.

Closes #98

### CODE REVIEW

File: packages/web/src/linkBridge.ts [hunk 1]
```diff
@@ -82,7 +82,8 @@ export const linkBridge = <
       ([methodName]) => methodName,
     );
     return {
-      addEventListener: (_eventName, _listener) => () => {},
+      addEventListener:
+        (_eventName: string, _listener: (...args: any[]) => void) => () => {},
```
Comment (gronxb) [inline packages/web/src/linkBridge.ts]:
```suggestion
      addEventListener: (_eventName, _listener) => () => {},
```

File: packages/react-native/src/integrations/bridge.ts [hunk 2]
```diff
@@ -171,16 +177,17 @@ export const SAFE_NATIVE_EMITTER_EMIT_BY_BRIDGE_ID = (
 export const SAFE_NATIVE_EMITTER_THROW_BY_BRIDGE_ID = (
   bridgeId: string,
   eventName: string,
+  serializedError: string | true,
 ) => `
     (function() {
         if (window.nativeEmitterMap && window.nativeEmitterMap['${bridgeId}']) {
-            window.nativeEmitterMap['${bridgeId}'].emit('${eventName}', {}, true);
+            window.nativeEmitterMap['${bridgeId}'].emit('${eventName}', {}, ${JSON.stringify(serializedError)});
```
Comment (gronxb) [inline packages/react-native/src/integrations/bridge.ts]: I noticed that `JSON.stringify(serializedError)` is being executed three times. Would it be better to execute it only once at the entry point of `SAFE_NATIVE_EMITTER_THROW_BY_BRIDGE_ID` and reuse that result?

**Review by gronxb — CHANGES_REQUESTED** [review]
Thanks for your contribution.  I’ve always been waiting for this PR. Thank you.

**Review by gronxb — APPROVED** [review]

File: packages/react-native/src/integrations/bridge.ts (hunk 2 above)
Comment (dioKR) [reply packages/react-native/src/integrations/bridge.ts]: Great suggestion! Should I open a follow-up PR for this?

Comment (gronxb) [reply packages/react-native/src/integrations/bridge.ts]: It’s just a one-liner, so I’ll take care of it. Thanks!! I’ll let you know again after I deploy it.

**Comment by gronxb** [comment]
Released in 1.7.9 !
